---
- name: check for existing wordpress installation
  stat:
    path: "{{ wordpress_root }}/wp-config.php"
  register: wp_config

- name: download wordpress tar
  shell:
    cmd: 'wget https://wordpress.org/latest.tar.gz -O /tmp/wp.tar.gz'
  when: not wp_config.stat.exists

- name: extract wordpress
  unarchive:
    src: /tmp/wp.tar.gz
    dest: "/tmp/"
    remote_src: yes
  become: yes
  when: not wp_config.stat.exists

- name: create wordpress root
  file:
    path: "{{ wordpress_root }}"
    state: directory
    owner: root
    group: root
  become: yes

- name: move wordpress files to wp root
  shell:
    cmd: "cp -r /tmp/wordpress/* {{ wordpress_root }}"
  become: yes
  when: not wp_config.stat.exists

- name: copy wp-config.php
  template:
    dest: "{{ wordpress_root }}/wp-config.php"
    src: "templates/wp-config.php.j2"
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
  become: yes
  register: wp_config_change

- name: change wordpress content owner
  file:
    path: "{{ wordpress_root }}"
    owner: "{{ wordpress_user }}"
    group: "{{ wordpress_group }}"
    recurse: yes
  become: yes

- name: accommodate SELinux
  shell:
    cmd: "chcon -R -t httpd_sys_content_t {{ wordpress_root }}"
  become: yes

- name: reload httpd
  service:
    name: httpd
    state: reloaded
  become: yes
  when: wp_config_change.changed or not wp_config.stat.exists
