- hosts: app
  name: Setup access and basic tools
  gather_facts: no
  become: yes
  vars_files:
    - ./vars/access.yml
  remote_user: "{{ access_user }}"
  tags:
    - access
  roles:
    - sjb9774.access
    - sjb9774.epel
    - sjb9774.wget

- hosts: app
  name: setup WordPress
  gather_facts: yes
  remote_user: "{{ access_user }}"
  tags:
      - site
  roles:
    - role: sjb9774.mysql
      tags:
        - mysql
    - role: sjb9774.git
      tags:
        - git
    - role: sjb9774.php
      tags:
        - php
    - role: sjb9774.httpd
      tags:
        - httpd
    - role: sjb9774.php-xdebug
      tags:
        - php
        - xdebug
      vars:
        xdebug_remote_host: "{{ ansible_hostname }}"
      when: include_xdebug
    - role: sjb9774.composer
    - role: sjb9774.svn
    - role: sjb9774.wordpress
      tags:
        - wordpress
    - role: sjb9774.certbot
      vars:
        - certbot_email: stephen.biston@gmail.com
        - certbot_domain: "{{ ansible_hostname }}"
      tags:
        - certbot
      when: include_certbot|default(False)
